/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionId } from './SessionId';
import {
    SessionIdFromJSON,
    SessionIdFromJSONTyped,
    SessionIdToJSON,
    SessionIdToJSONTyped,
} from './SessionId';

/**
 * 
 * @export
 * @interface ActivationData
 */
export interface ActivationData {
    /**
     * 
     * @type {SessionId}
     * @memberof ActivationData
     */
    sessionId: SessionId;
    /**
     * 
     * @type {string}
     * @memberof ActivationData
     */
    licenseKey: string;
}

/**
 * Check if a given object implements the ActivationData interface.
 */
export function instanceOfActivationData(value: object): value is ActivationData {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('licenseKey' in value) || value['licenseKey'] === undefined) return false;
    return true;
}

export function ActivationDataFromJSON(json: any): ActivationData {
    return ActivationDataFromJSONTyped(json, false);
}

export function ActivationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivationData {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': SessionIdFromJSON(json['sessionId']),
        'licenseKey': json['licenseKey'],
    };
}

export function ActivationDataToJSON(json: any): ActivationData {
    return ActivationDataToJSONTyped(json, false);
}

export function ActivationDataToJSONTyped(value?: ActivationData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': SessionIdToJSON(value['sessionId']),
        'licenseKey': value['licenseKey'],
    };
}

