/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Data } from './Data';
import {
    DataFromJSON,
    DataFromJSONTyped,
    DataToJSON,
    DataToJSONTyped,
} from './Data';

/**
 * 
 * @export
 * @interface APIV2AuthLoginPostResponse
 */
export interface APIV2AuthLoginPostResponse {
    /**
     * 
     * @type {Data}
     * @memberof APIV2AuthLoginPostResponse
     */
    data?: Data;
    /**
     * 
     * @type {number}
     * @memberof APIV2AuthLoginPostResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof APIV2AuthLoginPostResponse
     */
    statusText?: string;
}

/**
 * Check if a given object implements the APIV2AuthLoginPostResponse interface.
 */
export function instanceOfAPIV2AuthLoginPostResponse(value: object): value is APIV2AuthLoginPostResponse {
    return true;
}

export function APIV2AuthLoginPostResponseFromJSON(json: any): APIV2AuthLoginPostResponse {
    return APIV2AuthLoginPostResponseFromJSONTyped(json, false);
}

export function APIV2AuthLoginPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIV2AuthLoginPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DataFromJSON(json['data']),
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'statusText': json['statusText'] == null ? undefined : json['statusText'],
    };
}

export function APIV2AuthLoginPostResponseToJSON(json: any): APIV2AuthLoginPostResponse {
    return APIV2AuthLoginPostResponseToJSONTyped(json, false);
}

export function APIV2AuthLoginPostResponseToJSONTyped(value?: APIV2AuthLoginPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DataToJSON(value['data']),
        'statusCode': value['statusCode'],
        'statusText': value['statusText'],
    };
}

