/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Data1 } from './Data1';
import {
    Data1FromJSON,
    Data1FromJSONTyped,
    Data1ToJSON,
    Data1ToJSONTyped,
} from './Data1';

/**
 * 
 * @export
 * @interface APIV2AuthValidatePostResponse
 */
export interface APIV2AuthValidatePostResponse {
    /**
     * 
     * @type {Data1}
     * @memberof APIV2AuthValidatePostResponse
     */
    data?: Data1;
    /**
     * 
     * @type {number}
     * @memberof APIV2AuthValidatePostResponse
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof APIV2AuthValidatePostResponse
     */
    statusText?: string;
}

/**
 * Check if a given object implements the APIV2AuthValidatePostResponse interface.
 */
export function instanceOfAPIV2AuthValidatePostResponse(value: object): value is APIV2AuthValidatePostResponse {
    return true;
}

export function APIV2AuthValidatePostResponseFromJSON(json: any): APIV2AuthValidatePostResponse {
    return APIV2AuthValidatePostResponseFromJSONTyped(json, false);
}

export function APIV2AuthValidatePostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIV2AuthValidatePostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : Data1FromJSON(json['data']),
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'statusText': json['statusText'] == null ? undefined : json['statusText'],
    };
}

export function APIV2AuthValidatePostResponseToJSON(json: any): APIV2AuthValidatePostResponse {
    return APIV2AuthValidatePostResponseToJSONTyped(json, false);
}

export function APIV2AuthValidatePostResponseToJSONTyped(value?: APIV2AuthValidatePostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': Data1ToJSON(value['data']),
        'statusCode': value['statusCode'],
        'statusText': value['statusText'],
    };
}

