/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIV2AuthLoginPostRequest
 */
export interface APIV2AuthLoginPostRequest {
    /**
     * 
     * @type {boolean}
     * @memberof APIV2AuthLoginPostRequest
     */
    issueJWT?: boolean;
    /**
     * 
     * @type {string}
     * @memberof APIV2AuthLoginPostRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof APIV2AuthLoginPostRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the APIV2AuthLoginPostRequest interface.
 */
export function instanceOfAPIV2AuthLoginPostRequest(value: object): value is APIV2AuthLoginPostRequest {
    return true;
}

export function APIV2AuthLoginPostRequestFromJSON(json: any): APIV2AuthLoginPostRequest {
    return APIV2AuthLoginPostRequestFromJSONTyped(json, false);
}

export function APIV2AuthLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIV2AuthLoginPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'issueJWT': json['issueJWT'] == null ? undefined : json['issueJWT'],
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function APIV2AuthLoginPostRequestToJSON(json: any): APIV2AuthLoginPostRequest {
    return APIV2AuthLoginPostRequestToJSONTyped(json, false);
}

export function APIV2AuthLoginPostRequestToJSONTyped(value?: APIV2AuthLoginPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issueJWT': value['issueJWT'],
        'password': value['password'],
        'username': value['username'],
    };
}

