/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Jwt1 } from './Jwt1';
import {
    Jwt1FromJSON,
    Jwt1FromJSONTyped,
    Jwt1ToJSON,
    Jwt1ToJSONTyped,
} from './Jwt1';

/**
 * 
 * @export
 * @interface APIV2AuthValidatePostRequest
 */
export interface APIV2AuthValidatePostRequest {
    /**
     * 
     * @type {Jwt1}
     * @memberof APIV2AuthValidatePostRequest
     */
    jwt?: Jwt1;
}

/**
 * Check if a given object implements the APIV2AuthValidatePostRequest interface.
 */
export function instanceOfAPIV2AuthValidatePostRequest(value: object): value is APIV2AuthValidatePostRequest {
    return true;
}

export function APIV2AuthValidatePostRequestFromJSON(json: any): APIV2AuthValidatePostRequest {
    return APIV2AuthValidatePostRequestFromJSONTyped(json, false);
}

export function APIV2AuthValidatePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIV2AuthValidatePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'jwt': json['jwt'] == null ? undefined : Jwt1FromJSON(json['jwt']),
    };
}

export function APIV2AuthValidatePostRequestToJSON(json: any): APIV2AuthValidatePostRequest {
    return APIV2AuthValidatePostRequestToJSONTyped(json, false);
}

export function APIV2AuthValidatePostRequestToJSONTyped(value?: APIV2AuthValidatePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jwt': Jwt1ToJSON(value['jwt']),
    };
}

