/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface AppResponse
 */
export interface AppResponse {
    /**
     * 
     * @type {number}
     * @memberof AppResponse
     */
    totalProducts: number;
    /**
     * 
     * @type {Array<Product>}
     * @memberof AppResponse
     */
    products: Array<Product>;
}

/**
 * Check if a given object implements the AppResponse interface.
 */
export function instanceOfAppResponse(value: object): value is AppResponse {
    if (!('totalProducts' in value) || value['totalProducts'] === undefined) return false;
    if (!('products' in value) || value['products'] === undefined) return false;
    return true;
}

export function AppResponseFromJSON(json: any): AppResponse {
    return AppResponseFromJSONTyped(json, false);
}

export function AppResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalProducts': json['totalProducts'],
        'products': ((json['products'] as Array<any>).map(ProductFromJSON)),
    };
}

export function AppResponseToJSON(json: any): AppResponse {
    return AppResponseToJSONTyped(json, false);
}

export function AppResponseToJSONTyped(value?: AppResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalProducts': value['totalProducts'],
        'products': ((value['products'] as Array<any>).map(ProductToJSON)),
    };
}

