/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeatureFlags1 } from './FeatureFlags1';
import {
    FeatureFlags1FromJSON,
    FeatureFlags1FromJSONTyped,
    FeatureFlags1ToJSON,
    FeatureFlags1ToJSONTyped,
} from './FeatureFlags1';

/**
 * 
 * @export
 * @interface Data1
 */
export interface Data1 {
    /**
     * 
     * @type {FeatureFlags1}
     * @memberof Data1
     */
    featureFlags?: FeatureFlags1;
    /**
     * 
     * @type {boolean}
     * @memberof Data1
     */
    isValid?: boolean;
}

/**
 * Check if a given object implements the Data1 interface.
 */
export function instanceOfData1(value: object): value is Data1 {
    return true;
}

export function Data1FromJSON(json: any): Data1 {
    return Data1FromJSONTyped(json, false);
}

export function Data1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Data1 {
    if (json == null) {
        return json;
    }
    return {
        
        'featureFlags': json['feature_flags'] == null ? undefined : FeatureFlags1FromJSON(json['feature_flags']),
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
    };
}

export function Data1ToJSON(json: any): Data1 {
    return Data1ToJSONTyped(json, false);
}

export function Data1ToJSONTyped(value?: Data1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feature_flags': FeatureFlags1ToJSON(value['featureFlags']),
        'isValid': value['isValid'],
    };
}

