/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ff } from './Ff';
import {
    FfFromJSON,
    FfFromJSONTyped,
    FfToJSON,
    FfToJSONTyped,
} from './Ff';

/**
 * 
 * @export
 * @interface FeatureFlags1
 */
export interface FeatureFlags1 {
    /**
     * 
     * @type {Ff}
     * @memberof FeatureFlags1
     */
    ff?: Ff;
}

/**
 * Check if a given object implements the FeatureFlags1 interface.
 */
export function instanceOfFeatureFlags1(value: object): value is FeatureFlags1 {
    return true;
}

export function FeatureFlags1FromJSON(json: any): FeatureFlags1 {
    return FeatureFlags1FromJSONTyped(json, false);
}

export function FeatureFlags1FromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureFlags1 {
    if (json == null) {
        return json;
    }
    return {
        
        'ff': json['ff'] == null ? undefined : FfFromJSON(json['ff']),
    };
}

export function FeatureFlags1ToJSON(json: any): FeatureFlags1 {
    return FeatureFlags1ToJSONTyped(json, false);
}

export function FeatureFlags1ToJSONTyped(value?: FeatureFlags1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ff': FfToJSON(value['ff']),
    };
}

