/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureFlags
 */
export interface FeatureFlags {
    /**
     * 
     * @type {boolean}
     * @memberof FeatureFlags
     */
    isVendor?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FeatureFlags
     */
    isWhitelabeled?: boolean;
}

/**
 * Check if a given object implements the FeatureFlags interface.
 */
export function instanceOfFeatureFlags(value: object): value is FeatureFlags {
    return true;
}

export function FeatureFlagsFromJSON(json: any): FeatureFlags {
    return FeatureFlagsFromJSONTyped(json, false);
}

export function FeatureFlagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureFlags {
    if (json == null) {
        return json;
    }
    return {
        
        'isVendor': json['isVendor'] == null ? undefined : json['isVendor'],
        'isWhitelabeled': json['isWhitelabeled'] == null ? undefined : json['isWhitelabeled'],
    };
}

export function FeatureFlagsToJSON(json: any): FeatureFlags {
    return FeatureFlagsToJSONTyped(json, false);
}

export function FeatureFlagsToJSONTyped(value?: FeatureFlags | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isVendor': value['isVendor'],
        'isWhitelabeled': value['isWhitelabeled'],
    };
}

