/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ff
 */
export interface Ff {
    /**
     * 
     * @type {boolean}
     * @memberof Ff
     */
    isVendor?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Ff
     */
    isWhitelabeled?: boolean;
}

/**
 * Check if a given object implements the Ff interface.
 */
export function instanceOfFf(value: object): value is Ff {
    return true;
}

export function FfFromJSON(json: any): Ff {
    return FfFromJSONTyped(json, false);
}

export function FfFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ff {
    if (json == null) {
        return json;
    }
    return {
        
        'isVendor': json['isVendor'] == null ? undefined : json['isVendor'],
        'isWhitelabeled': json['isWhitelabeled'] == null ? undefined : json['isWhitelabeled'],
    };
}

export function FfToJSON(json: any): Ff {
    return FfToJSONTyped(json, false);
}

export function FfToJSONTyped(value?: Ff | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isVendor': value['isVendor'],
        'isWhitelabeled': value['isWhitelabeled'],
    };
}

