/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiV2ManifestsAppVersion404Response
 */
export interface GetApiV2ManifestsAppVersion404Response {
    /**
     * 
     * @type {number}
     * @memberof GetApiV2ManifestsAppVersion404Response
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof GetApiV2ManifestsAppVersion404Response
     */
    statusText?: string;
}

/**
 * Check if a given object implements the GetApiV2ManifestsAppVersion404Response interface.
 */
export function instanceOfGetApiV2ManifestsAppVersion404Response(value: object): value is GetApiV2ManifestsAppVersion404Response {
    return true;
}

export function GetApiV2ManifestsAppVersion404ResponseFromJSON(json: any): GetApiV2ManifestsAppVersion404Response {
    return GetApiV2ManifestsAppVersion404ResponseFromJSONTyped(json, false);
}

export function GetApiV2ManifestsAppVersion404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiV2ManifestsAppVersion404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'statusText': json['statusText'] == null ? undefined : json['statusText'],
    };
}

export function GetApiV2ManifestsAppVersion404ResponseToJSON(json: any): GetApiV2ManifestsAppVersion404Response {
    return GetApiV2ManifestsAppVersion404ResponseToJSONTyped(json, false);
}

export function GetApiV2ManifestsAppVersion404ResponseToJSONTyped(value?: GetApiV2ManifestsAppVersion404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'statusText': value['statusText'],
    };
}

