/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewResponse } from './ReviewResponse';
import {
    ReviewResponseFromJSON,
    ReviewResponseFromJSONTyped,
    ReviewResponseToJSON,
    ReviewResponseToJSONTyped,
} from './ReviewResponse';

/**
 * 
 * @export
 * @interface GetApiV2ProductsAppsReviews201Response
 */
export interface GetApiV2ProductsAppsReviews201Response {
    /**
     * 
     * @type {number}
     * @memberof GetApiV2ProductsAppsReviews201Response
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof GetApiV2ProductsAppsReviews201Response
     */
    statusText?: string;
    /**
     * 
     * @type {ReviewResponse}
     * @memberof GetApiV2ProductsAppsReviews201Response
     */
    data: ReviewResponse;
}

/**
 * Check if a given object implements the GetApiV2ProductsAppsReviews201Response interface.
 */
export function instanceOfGetApiV2ProductsAppsReviews201Response(value: object): value is GetApiV2ProductsAppsReviews201Response {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetApiV2ProductsAppsReviews201ResponseFromJSON(json: any): GetApiV2ProductsAppsReviews201Response {
    return GetApiV2ProductsAppsReviews201ResponseFromJSONTyped(json, false);
}

export function GetApiV2ProductsAppsReviews201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiV2ProductsAppsReviews201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'statusText': json['statusText'] == null ? undefined : json['statusText'],
        'data': ReviewResponseFromJSON(json['data']),
    };
}

export function GetApiV2ProductsAppsReviews201ResponseToJSON(json: any): GetApiV2ProductsAppsReviews201Response {
    return GetApiV2ProductsAppsReviews201ResponseToJSONTyped(json, false);
}

export function GetApiV2ProductsAppsReviews201ResponseToJSONTyped(value?: GetApiV2ProductsAppsReviews201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'statusText': value['statusText'],
        'data': ReviewResponseToJSON(value['data']),
    };
}

