/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiV2ManifestsAppVersion200Response
 */
export interface GetApiV2ManifestsAppVersion200Response {
    /**
     * 
     * @type {number}
     * @memberof GetApiV2ManifestsAppVersion200Response
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof GetApiV2ManifestsAppVersion200Response
     */
    statusText?: string;
    /**
     * 
     * @type {object}
     * @memberof GetApiV2ManifestsAppVersion200Response
     */
    data?: object;
}

/**
 * Check if a given object implements the GetApiV2ManifestsAppVersion200Response interface.
 */
export function instanceOfGetApiV2ManifestsAppVersion200Response(value: object): value is GetApiV2ManifestsAppVersion200Response {
    return true;
}

export function GetApiV2ManifestsAppVersion200ResponseFromJSON(json: any): GetApiV2ManifestsAppVersion200Response {
    return GetApiV2ManifestsAppVersion200ResponseFromJSONTyped(json, false);
}

export function GetApiV2ManifestsAppVersion200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiV2ManifestsAppVersion200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'statusText': json['statusText'] == null ? undefined : json['statusText'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function GetApiV2ManifestsAppVersion200ResponseToJSON(json: any): GetApiV2ManifestsAppVersion200Response {
    return GetApiV2ManifestsAppVersion200ResponseToJSONTyped(json, false);
}

export function GetApiV2ManifestsAppVersion200ResponseToJSONTyped(value?: GetApiV2ManifestsAppVersion200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'statusText': value['statusText'],
        'data': value['data'],
    };
}

