/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppResponse } from './AppResponse';
import {
    AppResponseFromJSON,
    AppResponseFromJSONTyped,
    AppResponseToJSON,
    AppResponseToJSONTyped,
} from './AppResponse';

/**
 * 
 * @export
 * @interface GetApiV2ProductsApps200Response
 */
export interface GetApiV2ProductsApps200Response {
    /**
     * 
     * @type {number}
     * @memberof GetApiV2ProductsApps200Response
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof GetApiV2ProductsApps200Response
     */
    statusText?: string;
    /**
     * 
     * @type {AppResponse}
     * @memberof GetApiV2ProductsApps200Response
     */
    data: AppResponse;
}

/**
 * Check if a given object implements the GetApiV2ProductsApps200Response interface.
 */
export function instanceOfGetApiV2ProductsApps200Response(value: object): value is GetApiV2ProductsApps200Response {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetApiV2ProductsApps200ResponseFromJSON(json: any): GetApiV2ProductsApps200Response {
    return GetApiV2ProductsApps200ResponseFromJSONTyped(json, false);
}

export function GetApiV2ProductsApps200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiV2ProductsApps200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'statusText': json['statusText'] == null ? undefined : json['statusText'],
        'data': AppResponseFromJSON(json['data']),
    };
}

export function GetApiV2ProductsApps200ResponseToJSON(json: any): GetApiV2ProductsApps200Response {
    return GetApiV2ProductsApps200ResponseToJSONTyped(json, false);
}

export function GetApiV2ProductsApps200ResponseToJSONTyped(value?: GetApiV2ProductsApps200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'statusText': value['statusText'],
        'data': AppResponseToJSON(value['data']),
    };
}

