/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Jwt
 */
export interface Jwt {
    /**
     * 
     * @type {string}
     * @memberof Jwt
     */
    token?: string;
    /**
     * 
     * @type {number}
     * @memberof Jwt
     */
    tokenExpires?: number;
}

/**
 * Check if a given object implements the Jwt interface.
 */
export function instanceOfJwt(value: object): value is Jwt {
    return true;
}

export function JwtFromJSON(json: any): Jwt {
    return JwtFromJSONTyped(json, false);
}

export function JwtFromJSONTyped(json: any, ignoreDiscriminator: boolean): Jwt {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'tokenExpires': json['token_expires'] == null ? undefined : json['token_expires'],
    };
}

export function JwtToJSON(json: any): Jwt {
    return JwtToJSONTyped(json, false);
}

export function JwtToJSONTyped(value?: Jwt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'token_expires': value['tokenExpires'],
    };
}

