/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Jwt1
 */
export interface Jwt1 {
    /**
     * 
     * @type {string}
     * @memberof Jwt1
     */
    token?: string;
}

/**
 * Check if a given object implements the Jwt1 interface.
 */
export function instanceOfJwt1(value: object): value is Jwt1 {
    return true;
}

export function Jwt1FromJSON(json: any): Jwt1 {
    return Jwt1FromJSONTyped(json, false);
}

export function Jwt1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Jwt1 {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function Jwt1ToJSON(json: any): Jwt1 {
    return Jwt1ToJSONTyped(json, false);
}

export function Jwt1ToJSONTyped(value?: Jwt1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

