/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderLineItem
 */
export interface OrderLineItem {
    /**
     * 
     * @type {number}
     * @memberof OrderLineItem
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof OrderLineItem
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof OrderLineItem
     */
    productId: number;
    /**
     * 
     * @type {number}
     * @memberof OrderLineItem
     */
    variationId: number;
    /**
     * 
     * @type {number}
     * @memberof OrderLineItem
     */
    quantity: number;
    /**
     * 
     * @type {object}
     * @memberof OrderLineItem
     */
    image: object;
}

/**
 * Check if a given object implements the OrderLineItem interface.
 */
export function instanceOfOrderLineItem(value: object): value is OrderLineItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('variationId' in value) || value['variationId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function OrderLineItemFromJSON(json: any): OrderLineItem {
    return OrderLineItemFromJSONTyped(json, false);
}

export function OrderLineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderLineItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'productId': json['product_id'],
        'variationId': json['variation_id'],
        'quantity': json['quantity'],
        'image': json['image'],
    };
}

export function OrderLineItemToJSON(json: any): OrderLineItem {
    return OrderLineItemToJSONTyped(json, false);
}

export function OrderLineItemToJSONTyped(value?: OrderLineItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'product_id': value['productId'],
        'variation_id': value['variationId'],
        'quantity': value['quantity'],
        'image': value['image'],
    };
}

