/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderBilling
 */
export interface OrderBilling {
    /**
     * 
     * @type {string}
     * @memberof OrderBilling
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderBilling
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderBilling
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderBilling
     */
    email?: string;
}

/**
 * Check if a given object implements the OrderBilling interface.
 */
export function instanceOfOrderBilling(value: object): value is OrderBilling {
    return true;
}

export function OrderBillingFromJSON(json: any): OrderBilling {
    return OrderBillingFromJSONTyped(json, false);
}

export function OrderBillingFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBilling {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'company': json['company'] == null ? undefined : json['company'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function OrderBillingToJSON(json: any): OrderBilling {
    return OrderBillingToJSONTyped(json, false);
}

export function OrderBillingToJSONTyped(value?: OrderBilling | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'company': value['company'],
        'email': value['email'],
    };
}

