/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostApiV2TokensRequest
 */
export interface PostApiV2TokensRequest {
    /**
     * 
     * @type {string}
     * @memberof PostApiV2TokensRequest
     */
    app: string;
    /**
     * 
     * @type {string}
     * @memberof PostApiV2TokensRequest
     */
    version: string;
}

/**
 * Check if a given object implements the PostApiV2TokensRequest interface.
 */
export function instanceOfPostApiV2TokensRequest(value: object): value is PostApiV2TokensRequest {
    if (!('app' in value) || value['app'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PostApiV2TokensRequestFromJSON(json: any): PostApiV2TokensRequest {
    return PostApiV2TokensRequestFromJSONTyped(json, false);
}

export function PostApiV2TokensRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiV2TokensRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'],
        'version': json['version'],
    };
}

export function PostApiV2TokensRequestToJSON(json: any): PostApiV2TokensRequest {
    return PostApiV2TokensRequestToJSONTyped(json, false);
}

export function PostApiV2TokensRequestToJSONTyped(value?: PostApiV2TokensRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': value['app'],
        'version': value['version'],
    };
}

