/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostApiV2DeviceLicenseActivateRequest
 */
export interface PostApiV2DeviceLicenseActivateRequest {
    /**
     * 
     * @type {string}
     * @memberof PostApiV2DeviceLicenseActivateRequest
     */
    licenseKey?: string;
}

/**
 * Check if a given object implements the PostApiV2DeviceLicenseActivateRequest interface.
 */
export function instanceOfPostApiV2DeviceLicenseActivateRequest(value: object): value is PostApiV2DeviceLicenseActivateRequest {
    return true;
}

export function PostApiV2DeviceLicenseActivateRequestFromJSON(json: any): PostApiV2DeviceLicenseActivateRequest {
    return PostApiV2DeviceLicenseActivateRequestFromJSONTyped(json, false);
}

export function PostApiV2DeviceLicenseActivateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiV2DeviceLicenseActivateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'licenseKey': json['licenseKey'] == null ? undefined : json['licenseKey'],
    };
}

export function PostApiV2DeviceLicenseActivateRequestToJSON(json: any): PostApiV2DeviceLicenseActivateRequest {
    return PostApiV2DeviceLicenseActivateRequestToJSONTyped(json, false);
}

export function PostApiV2DeviceLicenseActivateRequestToJSONTyped(value?: PostApiV2DeviceLicenseActivateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'licenseKey': value['licenseKey'],
    };
}

