/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostApiV2DeviceLicenseValidate200ResponseData } from './PostApiV2DeviceLicenseValidate200ResponseData';
import {
    PostApiV2DeviceLicenseValidate200ResponseDataFromJSON,
    PostApiV2DeviceLicenseValidate200ResponseDataFromJSONTyped,
    PostApiV2DeviceLicenseValidate200ResponseDataToJSON,
    PostApiV2DeviceLicenseValidate200ResponseDataToJSONTyped,
} from './PostApiV2DeviceLicenseValidate200ResponseData';

/**
 * 
 * @export
 * @interface PostApiV2DeviceLicenseValidate200Response
 */
export interface PostApiV2DeviceLicenseValidate200Response {
    /**
     * 
     * @type {PostApiV2DeviceLicenseValidate200ResponseData}
     * @memberof PostApiV2DeviceLicenseValidate200Response
     */
    data: PostApiV2DeviceLicenseValidate200ResponseData;
    /**
     * 
     * @type {number}
     * @memberof PostApiV2DeviceLicenseValidate200Response
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof PostApiV2DeviceLicenseValidate200Response
     */
    statusText?: string;
}

/**
 * Check if a given object implements the PostApiV2DeviceLicenseValidate200Response interface.
 */
export function instanceOfPostApiV2DeviceLicenseValidate200Response(value: object): value is PostApiV2DeviceLicenseValidate200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PostApiV2DeviceLicenseValidate200ResponseFromJSON(json: any): PostApiV2DeviceLicenseValidate200Response {
    return PostApiV2DeviceLicenseValidate200ResponseFromJSONTyped(json, false);
}

export function PostApiV2DeviceLicenseValidate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiV2DeviceLicenseValidate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PostApiV2DeviceLicenseValidate200ResponseDataFromJSON(json['data']),
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'statusText': json['statusText'] == null ? undefined : json['statusText'],
    };
}

export function PostApiV2DeviceLicenseValidate200ResponseToJSON(json: any): PostApiV2DeviceLicenseValidate200Response {
    return PostApiV2DeviceLicenseValidate200ResponseToJSONTyped(json, false);
}

export function PostApiV2DeviceLicenseValidate200ResponseToJSONTyped(value?: PostApiV2DeviceLicenseValidate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PostApiV2DeviceLicenseValidate200ResponseDataToJSON(value['data']),
        'statusCode': value['statusCode'],
        'statusText': value['statusText'],
    };
}

