/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostApiV2Tokens200ResponseData } from './PostApiV2Tokens200ResponseData';
import {
    PostApiV2Tokens200ResponseDataFromJSON,
    PostApiV2Tokens200ResponseDataFromJSONTyped,
    PostApiV2Tokens200ResponseDataToJSON,
    PostApiV2Tokens200ResponseDataToJSONTyped,
} from './PostApiV2Tokens200ResponseData';

/**
 * 
 * @export
 * @interface PostApiV2Tokens200Response
 */
export interface PostApiV2Tokens200Response {
    /**
     * 
     * @type {number}
     * @memberof PostApiV2Tokens200Response
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof PostApiV2Tokens200Response
     */
    statusText?: string;
    /**
     * 
     * @type {PostApiV2Tokens200ResponseData}
     * @memberof PostApiV2Tokens200Response
     */
    data: PostApiV2Tokens200ResponseData;
}

/**
 * Check if a given object implements the PostApiV2Tokens200Response interface.
 */
export function instanceOfPostApiV2Tokens200Response(value: object): value is PostApiV2Tokens200Response {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PostApiV2Tokens200ResponseFromJSON(json: any): PostApiV2Tokens200Response {
    return PostApiV2Tokens200ResponseFromJSONTyped(json, false);
}

export function PostApiV2Tokens200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiV2Tokens200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'statusText': json['statusText'] == null ? undefined : json['statusText'],
        'data': PostApiV2Tokens200ResponseDataFromJSON(json['data']),
    };
}

export function PostApiV2Tokens200ResponseToJSON(json: any): PostApiV2Tokens200Response {
    return PostApiV2Tokens200ResponseToJSONTyped(json, false);
}

export function PostApiV2Tokens200ResponseToJSONTyped(value?: PostApiV2Tokens200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'statusText': value['statusText'],
        'data': PostApiV2Tokens200ResponseDataToJSON(value['data']),
    };
}

