/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivationData } from './ActivationData';
import {
    ActivationDataFromJSON,
    ActivationDataFromJSONTyped,
    ActivationDataToJSON,
    ActivationDataToJSONTyped,
} from './ActivationData';

/**
 * 
 * @export
 * @interface PostApiV2DeviceLicenseActivate200Response
 */
export interface PostApiV2DeviceLicenseActivate200Response {
    /**
     * 
     * @type {ActivationData}
     * @memberof PostApiV2DeviceLicenseActivate200Response
     */
    data: ActivationData;
    /**
     * 
     * @type {number}
     * @memberof PostApiV2DeviceLicenseActivate200Response
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof PostApiV2DeviceLicenseActivate200Response
     */
    statusText?: string;
}

/**
 * Check if a given object implements the PostApiV2DeviceLicenseActivate200Response interface.
 */
export function instanceOfPostApiV2DeviceLicenseActivate200Response(value: object): value is PostApiV2DeviceLicenseActivate200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PostApiV2DeviceLicenseActivate200ResponseFromJSON(json: any): PostApiV2DeviceLicenseActivate200Response {
    return PostApiV2DeviceLicenseActivate200ResponseFromJSONTyped(json, false);
}

export function PostApiV2DeviceLicenseActivate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiV2DeviceLicenseActivate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ActivationDataFromJSON(json['data']),
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'statusText': json['statusText'] == null ? undefined : json['statusText'],
    };
}

export function PostApiV2DeviceLicenseActivate200ResponseToJSON(json: any): PostApiV2DeviceLicenseActivate200Response {
    return PostApiV2DeviceLicenseActivate200ResponseToJSONTyped(json, false);
}

export function PostApiV2DeviceLicenseActivate200ResponseToJSONTyped(value?: PostApiV2DeviceLicenseActivate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ActivationDataToJSON(value['data']),
        'statusCode': value['statusCode'],
        'statusText': value['statusText'],
    };
}

