/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostApiV2Tokens200ResponseDataToken } from './PostApiV2Tokens200ResponseDataToken';
import {
    PostApiV2Tokens200ResponseDataTokenFromJSON,
    PostApiV2Tokens200ResponseDataTokenFromJSONTyped,
    PostApiV2Tokens200ResponseDataTokenToJSON,
    PostApiV2Tokens200ResponseDataTokenToJSONTyped,
} from './PostApiV2Tokens200ResponseDataToken';

/**
 * 
 * @export
 * @interface PostApiV2Tokens200ResponseData
 */
export interface PostApiV2Tokens200ResponseData {
    /**
     * 
     * @type {PostApiV2Tokens200ResponseDataToken}
     * @memberof PostApiV2Tokens200ResponseData
     */
    token: PostApiV2Tokens200ResponseDataToken;
}

/**
 * Check if a given object implements the PostApiV2Tokens200ResponseData interface.
 */
export function instanceOfPostApiV2Tokens200ResponseData(value: object): value is PostApiV2Tokens200ResponseData {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function PostApiV2Tokens200ResponseDataFromJSON(json: any): PostApiV2Tokens200ResponseData {
    return PostApiV2Tokens200ResponseDataFromJSONTyped(json, false);
}

export function PostApiV2Tokens200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiV2Tokens200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'token': PostApiV2Tokens200ResponseDataTokenFromJSON(json['token']),
    };
}

export function PostApiV2Tokens200ResponseDataToJSON(json: any): PostApiV2Tokens200ResponseData {
    return PostApiV2Tokens200ResponseDataToJSONTyped(json, false);
}

export function PostApiV2Tokens200ResponseDataToJSONTyped(value?: PostApiV2Tokens200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': PostApiV2Tokens200ResponseDataTokenToJSON(value['token']),
    };
}

