/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostApiV2Tokens200ResponseDataToken
 */
export interface PostApiV2Tokens200ResponseDataToken {
    /**
     * 
     * @type {string}
     * @memberof PostApiV2Tokens200ResponseDataToken
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof PostApiV2Tokens200ResponseDataToken
     */
    password: string;
}

/**
 * Check if a given object implements the PostApiV2Tokens200ResponseDataToken interface.
 */
export function instanceOfPostApiV2Tokens200ResponseDataToken(value: object): value is PostApiV2Tokens200ResponseDataToken {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function PostApiV2Tokens200ResponseDataTokenFromJSON(json: any): PostApiV2Tokens200ResponseDataToken {
    return PostApiV2Tokens200ResponseDataTokenFromJSONTyped(json, false);
}

export function PostApiV2Tokens200ResponseDataTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiV2Tokens200ResponseDataToken {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function PostApiV2Tokens200ResponseDataTokenToJSON(json: any): PostApiV2Tokens200ResponseDataToken {
    return PostApiV2Tokens200ResponseDataTokenToJSONTyped(json, false);
}

export function PostApiV2Tokens200ResponseDataTokenToJSONTyped(value?: PostApiV2Tokens200ResponseDataToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

