/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductMetadata
 */
export interface ProductMetadata {
    /**
     * 
     * @type {number}
     * @memberof ProductMetadata
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductMetadata
     */
    name: string;
    /**
     * 
     * @type {object}
     * @memberof ProductMetadata
     */
    value?: object;
}

/**
 * Check if a given object implements the ProductMetadata interface.
 */
export function instanceOfProductMetadata(value: object): value is ProductMetadata {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProductMetadataFromJSON(json: any): ProductMetadata {
    return ProductMetadataFromJSONTyped(json, false);
}

export function ProductMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function ProductMetadataToJSON(json: any): ProductMetadata {
    return ProductMetadataToJSONTyped(json, false);
}

export function ProductMetadataToJSONTyped(value?: ProductMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'value': value['value'],
    };
}

