/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewRequestData
 */
export interface ReviewRequestData {
    /**
     * 
     * @type {number}
     * @memberof ReviewRequestData
     */
    productId: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewRequestData
     */
    review: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewRequestData
     */
    reviewer: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewRequestData
     */
    reviewerEmail: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewRequestData
     */
    rating: number;
}

/**
 * Check if a given object implements the ReviewRequestData interface.
 */
export function instanceOfReviewRequestData(value: object): value is ReviewRequestData {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('review' in value) || value['review'] === undefined) return false;
    if (!('reviewer' in value) || value['reviewer'] === undefined) return false;
    if (!('reviewerEmail' in value) || value['reviewerEmail'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    return true;
}

export function ReviewRequestDataFromJSON(json: any): ReviewRequestData {
    return ReviewRequestDataFromJSONTyped(json, false);
}

export function ReviewRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewRequestData {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['product_id'],
        'review': json['review'],
        'reviewer': json['reviewer'],
        'reviewerEmail': json['reviewer_email'],
        'rating': json['rating'],
    };
}

export function ReviewRequestDataToJSON(json: any): ReviewRequestData {
    return ReviewRequestDataToJSONTyped(json, false);
}

export function ReviewRequestDataToJSONTyped(value?: ReviewRequestData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_id': value['productId'],
        'review': value['review'],
        'reviewer': value['reviewer'],
        'reviewer_email': value['reviewerEmail'],
        'rating': value['rating'],
    };
}

