/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewResponseReview
 */
export interface ReviewResponseReview {
    /**
     * 
     * @type {number}
     * @memberof ReviewResponseReview
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseReview
     */
    dateCreated: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseReview
     */
    dateCreatedGmt: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewResponseReview
     */
    productId: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseReview
     */
    productName: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseReview
     */
    productPermalink: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseReview
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseReview
     */
    reviewer: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseReview
     */
    reviewerEmail: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseReview
     */
    review: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewResponseReview
     */
    rating: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReviewResponseReview
     */
    verified: boolean;
}

/**
 * Check if a given object implements the ReviewResponseReview interface.
 */
export function instanceOfReviewResponseReview(value: object): value is ReviewResponseReview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('dateCreated' in value) || value['dateCreated'] === undefined) return false;
    if (!('dateCreatedGmt' in value) || value['dateCreatedGmt'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('productName' in value) || value['productName'] === undefined) return false;
    if (!('productPermalink' in value) || value['productPermalink'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('reviewer' in value) || value['reviewer'] === undefined) return false;
    if (!('reviewerEmail' in value) || value['reviewerEmail'] === undefined) return false;
    if (!('review' in value) || value['review'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('verified' in value) || value['verified'] === undefined) return false;
    return true;
}

export function ReviewResponseReviewFromJSON(json: any): ReviewResponseReview {
    return ReviewResponseReviewFromJSONTyped(json, false);
}

export function ReviewResponseReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewResponseReview {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dateCreated': json['date_created'],
        'dateCreatedGmt': json['date_created_gmt'],
        'productId': json['product_id'],
        'productName': json['product_name'],
        'productPermalink': json['product_permalink'],
        'status': json['status'],
        'reviewer': json['reviewer'],
        'reviewerEmail': json['reviewer_email'],
        'review': json['review'],
        'rating': json['rating'],
        'verified': json['verified'],
    };
}

export function ReviewResponseReviewToJSON(json: any): ReviewResponseReview {
    return ReviewResponseReviewToJSONTyped(json, false);
}

export function ReviewResponseReviewToJSONTyped(value?: ReviewResponseReview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date_created': value['dateCreated'],
        'date_created_gmt': value['dateCreatedGmt'],
        'product_id': value['productId'],
        'product_name': value['productName'],
        'product_permalink': value['productPermalink'],
        'status': value['status'],
        'reviewer': value['reviewer'],
        'reviewer_email': value['reviewerEmail'],
        'review': value['review'],
        'rating': value['rating'],
        'verified': value['verified'],
    };
}

