/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewResponseReview } from './ReviewResponseReview';
import {
    ReviewResponseReviewFromJSON,
    ReviewResponseReviewFromJSONTyped,
    ReviewResponseReviewToJSON,
    ReviewResponseReviewToJSONTyped,
} from './ReviewResponseReview';

/**
 * 
 * @export
 * @interface ReviewResponse
 */
export interface ReviewResponse {
    /**
     * 
     * @type {ReviewResponseReview}
     * @memberof ReviewResponse
     */
    review: ReviewResponseReview;
}

/**
 * Check if a given object implements the ReviewResponse interface.
 */
export function instanceOfReviewResponse(value: object): value is ReviewResponse {
    if (!('review' in value) || value['review'] === undefined) return false;
    return true;
}

export function ReviewResponseFromJSON(json: any): ReviewResponse {
    return ReviewResponseFromJSONTyped(json, false);
}

export function ReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'review': ReviewResponseReviewFromJSON(json['review']),
    };
}

export function ReviewResponseToJSON(json: any): ReviewResponse {
    return ReviewResponseToJSONTyped(json, false);
}

export function ReviewResponseToJSONTyped(value?: ReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'review': ReviewResponseReviewToJSON(value['review']),
    };
}

