/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewRequestData } from './ReviewRequestData';
import {
    ReviewRequestDataFromJSON,
    ReviewRequestDataFromJSONTyped,
    ReviewRequestDataToJSON,
    ReviewRequestDataToJSONTyped,
} from './ReviewRequestData';

/**
 * 
 * @export
 * @interface ReviewRequest
 */
export interface ReviewRequest {
    /**
     * 
     * @type {ReviewRequestData}
     * @memberof ReviewRequest
     */
    data?: ReviewRequestData;
    /**
     * 
     * @type {string}
     * @memberof ReviewRequest
     */
    jwt?: string;
}

/**
 * Check if a given object implements the ReviewRequest interface.
 */
export function instanceOfReviewRequest(value: object): value is ReviewRequest {
    return true;
}

export function ReviewRequestFromJSON(json: any): ReviewRequest {
    return ReviewRequestFromJSONTyped(json, false);
}

export function ReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ReviewRequestDataFromJSON(json['data']),
        'jwt': json['jwt'] == null ? undefined : json['jwt'],
    };
}

export function ReviewRequestToJSON(json: any): ReviewRequest {
    return ReviewRequestToJSONTyped(json, false);
}

export function ReviewRequestToJSONTyped(value?: ReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ReviewRequestDataToJSON(value['data']),
        'jwt': value['jwt'],
    };
}

