/* tslint:disable */
/* eslint-disable */
/**
 * FLECS Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';

/**
 * 
 * @export
 * @interface Subscriptions
 */
export interface Subscriptions {
    /**
     * 
     * @type {number}
     * @memberof Subscriptions
     */
    totalSubscriptions: number;
    /**
     * 
     * @type {Array<Order>}
     * @memberof Subscriptions
     */
    subscriptions: Array<Order>;
}

/**
 * Check if a given object implements the Subscriptions interface.
 */
export function instanceOfSubscriptions(value: object): value is Subscriptions {
    if (!('totalSubscriptions' in value) || value['totalSubscriptions'] === undefined) return false;
    if (!('subscriptions' in value) || value['subscriptions'] === undefined) return false;
    return true;
}

export function SubscriptionsFromJSON(json: any): Subscriptions {
    return SubscriptionsFromJSONTyped(json, false);
}

export function SubscriptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscriptions {
    if (json == null) {
        return json;
    }
    return {
        
        'totalSubscriptions': json['totalSubscriptions'],
        'subscriptions': ((json['subscriptions'] as Array<any>).map(OrderFromJSON)),
    };
}

export function SubscriptionsToJSON(json: any): Subscriptions {
    return SubscriptionsToJSONTyped(json, false);
}

export function SubscriptionsToJSONTyped(value?: Subscriptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalSubscriptions': value['totalSubscriptions'],
        'subscriptions': ((value['subscriptions'] as Array<any>).map(OrderToJSON)),
    };
}

